package com.fadli.compapp.model

import com.fadli.compapp.R

object FakeHeroDataSource {
    val dummyHeroes = listOf(
        Hero(1, R.drawable.hero_1, "Abdul Muis","Abdoel Moeis (bahasa Arab: عبد المعز 'Abd Al-Mu'iz\u200E) (3 Juli 1886 – 17 Juni 1959) adalah seorang sastrawan, politikus, dan wartawan Indonesia. Dia merupakan pengurus besar Sarekat Islam dan pernah menjadi anggota Volksraad mewakili organisasi tersebut. Abdoel Moeis dikukuhkan sebagai Pahlawan Nasional yang pertama oleh Presiden RI, Soekarno, pada 30 Agustus 1959."),
        Hero(2, R.drawable.hero_2, "Ki Hajar Dewantara","Ki Hadjar Dewantara lahir di Yogyakarta pada tanggal 2 Mei 1889 dengan nama Raden Mas Soewardi Soeryaningrat. Ki Hajar Dewantara dibesarkan di lingkungan keluarga kraton Yogyakarta. Saat genap berusia 40 tahun menurut hitungan Tahun Caka, Raden Mas Soewardi Soeryaningrat berganti nama menjadi Ki Hadjar Dewantara. Semenjak saat itu, Ki Hadjar Dewantara tidak lagi menggunakan gelar kebangsawanan di depan namanya."),
        Hero(3, R.drawable.hero_3, "R.M. Surjopranoto","Raden Mas Suryopranoto merupakan seorang Pahlawan Nasional yang berjuluk Raja Mogok. Julukan itu didapat karena Suryopranoto memimpin para buruh melancarkan gerakan mogok kerja untuk memprotes kolonial Belanda. Suryopranoto juga membentuk beberapa organisasi buruh seperti Adhi Dharma, Prawiro Padjojo ing Joedo, hingga Personeel Fabriek Bond."),
        Hero(4, R.drawable.hero_4, "Mohammad Hoesni Thamrin","Thamrin adalah tokoh Betawi yang memiliki darah Belanda dari kakeknya, sedangkan ayahnya seorang Wedana tahun 1908 di bawah Bupati. Setelah menyelesaikan pendidikannya di sebuah sekolah Belanda Koning Willem II, Thamrin bekerja di kepemerintahan sebelum akhirnya bekerja di perusahaan perkapalan Koniklijke Paketvaart-Maatschappij tahun 1927."),
        Hero(5, R.drawable.hero_5, "KH. Samanhudi","Samanhudi tokoh yang terkenal sebagai pejuang dan pendiri Sarekat Dagang Islam ini lahir di Laweyan, Surakarta Jawa Tengah pada tahun 1868. Masyarakat sekitarnya sering memanggilnya dengan panggilan Kyai Haji Samanhudi. Dia juga memiliki nama kecil Sudarno Nadi, pemberian kedua orang tuanya dari sejak lahir. Latar belakang pendidikan Samanhudi hanya sampai tingkat Sekolah Dasar, akan tetapi walaupun Samanhudi tidak melanjutkan pendidikannya, dia tetap belajar mendalami ilmu Agama Islam di kota Surabaya."),
        Hero(6, R.drawable.hero_6, "H.O.S. Cokroaminoto","HOS Cokroaminoto lahir di Bakur, Madiun, Jawa Timur pada 16 Agustus 1882, dan mengembuskan napas terakhirnya di usia 52 tahun, tepatnya pada 17 Desember 1934. Ia merupakan keturunan bangsawan, ayahnya, R.M. Tjokroamiseno, seorang wedana atau asisten bupati. Sedangkan sang kakek, R.M. Adipati Tjokronegoro, pernah menjabat Bupati Ponorogo"),
        Hero(7, R.drawable.hero_7, "Danudirja Setiabudi","Danudirja Setiabudi atau Douwes Dekker lahir di Pasuruan, Jawa Timur, tanggal 8 Oktober 1879. Danudirja merupakan seorang Indo (Belanda-Jawa)"),
        Hero(8, R.drawable.hero_8, "Si Singamangaradja XII","Sisingamangaradja XII yang bernama asli Patuan Besar Ompu Pulo Batu lahir di Bakkara, Tapanuli, pada 1849.  Ia adalah penerus ayahnya, Sisingamangaradja XI, yang meninggal pada 1876."),
        Hero(9, R.drawable.hero_9, "Dr. G.S.S.J Ratulangie","Dr. Gerungan Saul Samuel Jacob (GSSJ) Ratulangi, pahlawan dari Tanah Minahasa, menjadi pembaca ulang proklamasi di hadapan warganya. Diasingkan ke pedalaman Papua tak membuat dirinya lekang dari sebutan \\'tuan-tuan merdeka\\'.Sam Ratulangi, panggilannya, lahir di Tondano, Sulawesi Utara, pada 5 November 1890. Ia lahir di keluarga pamong, ayahnya Kepala Distrik Kasendukan saat itu.Baca artikel CNN Indonesia \"Sam Ratulangi, Tuan-tuan Merdeka dari Minahasa"),
        Hero(10, R.drawable.hero_10, "DR. Sutomo","Sutomo (dr. Soetomo, lahir di Ngepeh, Loceret, Nganjuk, Jawa Timur, 30 Juli 1888 – meninggal di Surabaya, Jawa Timur, 30 Mei 1938 pada umur 49 tahun) adalah tokoh pendiri Budi Utomo, organisasi pergerakan yang pertama di Indonesia."),
        Hero(11, R.drawable.hero_11, "KH. Akhmad Dahlan","Ahmad Dahlan memiliki nama kecil Muhammad Darwis. Ia adalah anak keempat dari tujuh bersaudara dan termasuk keturunan dari Mulana Malik Ibrahin yaitu adalah salah seorang terkemuka di antara para walisongo, yaitu pelopor dari penyebaran agama Islam di Jawa."),
        Hero(12, R.drawable.hero_12, "KH. Agus Salim","Agus Salim adalah pejuang kemerdekaan yang dinobatkan sebagai Pahlawan Nasional Indonesia pada 27 Desember 1961, melalui Keppres Nomor 657 tahun 1961."),
    )
}